config:
  export_directory: /home/wso2user/.wso2apictl/exported
  http_request_timeout: 10000
  kubernetes_mode: false
  token_type: JWT
environments:
  sample-env1:
    admin: https://localhost:9443
    publisher: https://localhost:9443
    apim: https://localhost:9443
    devportal: https://localhost:9443
    registration: https://localhost:9443
    token: https://localhost:8243/token
  sample-env2:
    admin:
    publisher:
    apim: https://wso2am:9443
    devportal:
    registration:
    token: https://wso2am:8243/token
  sample-env3:
    admin: https://localhost:9443
    publisher: https://localhost:9443
    apim:
    devportal: https://localhost:9443
    registration: https://localhost:9443
    token: https://localhost:8243/token
