config:
  http_request_timeout: 1000000
  export_directory: /home/user/Desktop/exported
environments:
  dev:
    publisher_endpoint: https://localhost:9292/api/am/publisher/v1.0
    registration_endpoint: https://localhost:9443/identity/connect/register
    token_endpoint: https://localhost:9443/oauth2/token
  testEnv:
    publisher_endpoint: publisher
    registration_endpoint: registration
    token_endpoint: token
