# version of the wso2 api manager (state as either 2.* or 3.*; eg: 2.6)
apim_version: 2.6

# endpoints of the wso2 api manager
apim_endpoints:
  token_registration_endpoint: /client-registration/v0.14/register
  token_endpoint: /token
  publisher_api: /api/am/publisher/v0.14/apis
  store_application: /api/am/store/v0.14/applications
  store_subscription: /api/am/store/v0.14/subscriptions
  user_signup: /store/site/blocks/user/sign-up/ajax/user-add.jag
  delete_user: /services/RemoteUserStoreManagerService.RemoteUserStoreManagerServiceHttpsSoap11Endpoint

# api manager management console ports and configurations
management_console:
  protocol: https
  host: 
  servlet_transport_port_https: 9443
  servlet_transport_port_http: 9763

api_manager:
  nio_pt_transport_port: 8243

# details of Applications
apps:
  - name: Online Shopping
    description: This is an app allowing users to find places to buy their items, food or anything. A User can search for an item, find places, available quantities and their prices and order items through the app. Users can also do the payment when ordering. Also this app notifies users about recently released items and other recent news updates
    api_subscriptions: News,Places,Payment

  - name: Taxi
    description: This is a taxi app like Uber or Pickme where users can book cabs. App allows users to find rides for given destinations, book a ride, track ride info and do payments using credit/ debit cards
    api_subscriptions: Map,Places,Weather,Payment

  - name: CricScore
    description: This is a cricket app like Cricbuzz or Espn cric info where users can get updates about cricket matches, teams and players. App provides users with latest cric news updates. Also users can get live notification for ongoing matches
    api_subscriptions: News,Cricket
