# definitions for APIs which will be created by the scenario
api:
  throttling_tier: Unlimited
  visibility: PUBLIC
  production_endpoint: https://localhost:9443/am/sample/pizzashack/v1/api/
  sandbox_endpoint: https://localhost:9443/am/sample/pizzashack/v1/api/

# definitions for applications which will be created by the scenario
application:
  throttling_tier: Unlimited
  token_validity_period: -1

# subscription tier to be used when subscribing APIs
subscription_tier: Unlimited

# name of the scenario folder
scenario_name: scenario_example

# details for all hosted APIs. Traffic tool will invoke according to these configurations
api_host:
  protocol: https
  ip: 10.100.8.34
  port: 8243

# configurations for the traffic tool processes
tool_config:
  no_of_users: 100
  max_connection_refuse_count: 50
  no_of_data_points: 10000
  heavy_traffic: false

# payloads to send with POST and DELETE requests
payloads:
  post:
    - {"customerName": "customer_1","delivered": true,"address": "customer1_address","pizzaType": "customer_pizza","creditCardNumber": "customer_credit_card","quantity": 0,"orderId": "1"}
    - {"customerName": "customer_2","delivered": true,"address": "customer2_address","pizzaType": "customer_pizza","creditCardNumber": "customer_credit_card","quantity": 4,"orderId": "2"}
    - {"customerName": "customer_3","delivered": true,"address": "customer3_address","pizzaType": "customer_pizza","creditCardNumber": "customer_credit_card","quantity": 1,"orderId": "3"}

  delete:


# Traffic tool will randomly append one of the following user agents to the request header
user_agents:
  - Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.9.1.3) Gecko/20090913 Firefox/3.5.3
  - Mozilla/5.0 (Windows; U; Windows NT 6.1; en; rv:1.9.1.3) Gecko/20090824 Firefox/3.5.3 (.NET CLR 3.5.30729)
  - Mozilla/5.0 (Windows; U; Windows NT 5.2; en-US; rv:1.9.1.3) Gecko/20090824 Firefox/3.5.3 (.NET CLR 3.5.30729)
  - Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.1.1) Gecko/20090718 Firefox/3.5.1
  - Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/532.1 (KHTML, like Gecko) Chrome/4.0.219.6 Safari/532.1
  - Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; InfoPath.2)
  - Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; SLCC1; .NET CLR 2.0.50727; .NET CLR 1.1.4322; .NET CLR 3.5.30729; .NET CLR 3.0.30729)
  - Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.2; Win64; x64; Trident/4.0)
  - Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; SV1; .NET CLR 2.0.50727; InfoPath.2)
  - Mozilla/5.0 (Windows; U; MSIE 7.0; Windows NT 6.0; en-US)
  - Mozilla/4.0 (compatible; MSIE 6.1; Windows XP)
  - Opera/9.80 (Windows NT 5.2; U; ru) Presto/2.5.22 Version/10.51
